
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: password

development:
  <<: *default
  database: nagayandb_development

test:
  <<: *default
  database: nagayandb_test

production:
  <<: *default
  database: nagayandb_production
  username: nagayandb
  password: <%= ENV['NAGAYANDB_DATABASE_PASSWORD'] %>
